name: Clean

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    
    permissions:
      actions: write
      contents: read
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Weekly Artifact Cleanup
        uses: jimschubert/delete-artifacts-action@v1
        with:
          log_level: 'warning'
          min_bytes: '0'